packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '2': true
  '"': true
  ',': true
  '-': true
  ':': true
  a: true
  b: true
  c: true
  d: true
  e: true
  f: true
  h: true
  i: true
  j: true
  l: true
  o: true
  p: true
  r: true
  s: true
  t: true
  u: true
  '{': true
  '}': true
